import {GetObjectCommand, PutObjectCommand, S3Client} from "@aws-sdk/client-s3";
import { env } from "@repo/env/server";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";
export const s3 = new S3Client({
    region:env.AWS_REGION,
    credentials:{
       accessKeyId:env.AWS_ACCESS_KEY_ID,
       secretAccessKey:env.AWS_SECRET_ACCESS_KEY,
    }
});

/**
 In S3 every file/folder has a unique key which is the path to the file/folder.
 ^Pre-Signed Urls: 
   - A pre-signed URL is a temporary URL that grants temporary access to a private S3 object. It is generated by an AWS account and can be used by anyone to access the object without needing AWS credentials.
   - Purpose: It allows secure temporary access to private objects without exposing credentials.
   
   - Use Case: Generating presigned URLs for uploading large files directly to S3 from Frontend, bypassing your server for the heavy lifting.
 
 
 
 */

export const generateUploadUrl = async(fileName:string)=>{
    const cleanFileName = fileName.replace(/\s+/g,'').toLowerCase();
    const uniqueKey = `uploads/${cleanFileName}`;

    // ^PutObjectCommand: This command is used to upload an object to S3.
    const PutCommand = new PutObjectCommand({
        Bucket:env.BUCKET_NAME,
        Key:uniqueKey,
        ContentType:fileName.split('.').pop(),
    })

    const GetCommand = new GetObjectCommand({
        Bucket:env.BUCKET_NAME,
        Key:uniqueKey,
    })

    // ^ An Upload URL is a temporary presigned URL that allows a client to upload a file directly to S3.
    // It is generated using the AWS SDK.
    const fileUrl = `https://${env.BUCKET_NAME}.s3.${env.AWS_REGION}.amazonaws.com/${uniqueKey}`;

    const uploadUrl = await getSignedUrl(s3, PutCommand, {
    expiresIn: 300,
  });
     
     return {uploadUrl,fileUrl}
}



